//! Codegen: Manifest -> Rust source for a `lib.rs` exposing
//! `pub fn install(env: &Env)`.
//!
//! The output is a single self-contained file. We deliberately keep it
//! simple-and-explicit (no quote!/syn macros, no proc-macro deps) so
//! that the generated code is easy to read and to diff in golden tests.

use crate::manifest::{BindgenError, Function, Manifest, Method, Type};
use std::fmt::Write as _;

pub fn generate_install_rs(m: &Manifest) -> Result<String, BindgenError> {
    let mut out = String::new();
    write_header(&mut out, m);
    write_helpers(&mut out);

    // One Rust fn per cljrs builtin. Names are derived from clj-name with
    // non-ident chars replaced so they survive the Rust parser.
    for f in &m.fns {
        write_fn_shim(&mut out, m, f)?;
    }
    for me in &m.methods {
        write_method_shim(&mut out, me)?;
    }

    write_install(&mut out, m);
    Ok(out)
}

fn write_header(out: &mut String, m: &Manifest) {
    let _ = writeln!(
        out,
        "// AUTO-GENERATED by cljrs-bindgen. DO NOT EDIT.\n\
         // Source manifest binds crate `{}` v{} into namespace `{}`.\n",
        m.crate_.name, m.crate_.version, m.crate_.ns
    );
    let _ = writeln!(out, "#![allow(unused_imports, unused_variables, dead_code)]\n");
    let _ = writeln!(out, "use cljrs::env::Env;");
    let _ = writeln!(out, "use cljrs::error::{{Error, Result}};");
    let _ = writeln!(out, "use cljrs::value::{{Builtin, Value}};");
    let _ = writeln!(out, "use std::sync::Arc;");
    for imp in &m.crate_.imports {
        let _ = writeln!(out, "use {};", imp);
    }
    let _ = writeln!(out);
}

/// All marshalling helpers used by the generated shims. Emitted inline
/// (rather than imported) to keep the output a single self-contained
/// file — easier to diff, easier to drop into a fresh crate.
fn write_helpers(out: &mut String) {
    out.push_str(HELPERS);
    out.push('\n');
}

const HELPERS: &str = r#"
fn bind(env: &Env, name: &'static str, f: fn(&[Value]) -> Result<Value>) {
    env.define_global(name, Value::Builtin(Builtin::new_static(name, f)));
}

fn arg_i64(args: &[Value], idx: usize, name: &str) -> Result<i64> {
    match args.get(idx) {
        Some(Value::Int(i)) => Ok(*i),
        Some(v) => Err(Error::Type(format!(
            "{name}: arg {idx} must be int, got {}", v.type_name()
        ))),
        None => Err(Error::Eval(format!("{name}: missing arg {idx}"))),
    }
}

fn arg_f64(args: &[Value], idx: usize, name: &str) -> Result<f64> {
    match args.get(idx) {
        Some(Value::Float(f)) => Ok(*f),
        Some(Value::Int(i)) => Ok(*i as f64),
        Some(v) => Err(Error::Type(format!(
            "{name}: arg {idx} must be number, got {}", v.type_name()
        ))),
        None => Err(Error::Eval(format!("{name}: missing arg {idx}"))),
    }
}

fn arg_bool(args: &[Value], idx: usize, name: &str) -> Result<bool> {
    match args.get(idx) {
        Some(Value::Bool(b)) => Ok(*b),
        Some(v) => Err(Error::Type(format!(
            "{name}: arg {idx} must be bool, got {}", v.type_name()
        ))),
        None => Err(Error::Eval(format!("{name}: missing arg {idx}"))),
    }
}

fn arg_str(args: &[Value], idx: usize, name: &str) -> Result<Arc<str>> {
    match args.get(idx) {
        Some(Value::Str(s)) => Ok(Arc::clone(s)),
        Some(v) => Err(Error::Type(format!(
            "{name}: arg {idx} must be string, got {}", v.type_name()
        ))),
        None => Err(Error::Eval(format!("{name}: missing arg {idx}"))),
    }
}

fn arg_vec_i64(args: &[Value], idx: usize, name: &str) -> Result<Vec<i64>> {
    match args.get(idx) {
        Some(Value::Vector(xs)) => xs.iter().enumerate().map(|(i, v)| match v {
            Value::Int(n) => Ok(*n),
            other => Err(Error::Type(format!(
                "{name}: arg {idx}[{i}] must be int, got {}", other.type_name()
            ))),
        }).collect(),
        Some(Value::List(xs)) => xs.iter().enumerate().map(|(i, v)| match v {
            Value::Int(n) => Ok(*n),
            other => Err(Error::Type(format!(
                "{name}: arg {idx}[{i}] must be int, got {}", other.type_name()
            ))),
        }).collect(),
        Some(v) => Err(Error::Type(format!(
            "{name}: arg {idx} must be vector of int, got {}", v.type_name()
        ))),
        None => Err(Error::Eval(format!("{name}: missing arg {idx}"))),
    }
}

fn arg_vec_f64(args: &[Value], idx: usize, name: &str) -> Result<Vec<f64>> {
    match args.get(idx) {
        Some(Value::Vector(xs)) => xs.iter().enumerate().map(|(i, v)| match v {
            Value::Float(n) => Ok(*n),
            Value::Int(n) => Ok(*n as f64),
            other => Err(Error::Type(format!(
                "{name}: arg {idx}[{i}] must be number, got {}", other.type_name()
            ))),
        }).collect(),
        Some(Value::List(xs)) => xs.iter().enumerate().map(|(i, v)| match v {
            Value::Float(n) => Ok(*n),
            Value::Int(n) => Ok(*n as f64),
            other => Err(Error::Type(format!(
                "{name}: arg {idx}[{i}] must be number, got {}", other.type_name()
            ))),
        }).collect(),
        Some(v) => Err(Error::Type(format!(
            "{name}: arg {idx} must be vector of number, got {}", v.type_name()
        ))),
        None => Err(Error::Eval(format!("{name}: missing arg {idx}"))),
    }
}

fn arg_opaque<T: 'static + Send + Sync>(
    args: &[Value], idx: usize, tag: &str, name: &str,
) -> Result<Arc<T>> {
    match args.get(idx) {
        Some(Value::Opaque { tag: t, inner }) if t.as_ref() == tag => {
            Arc::clone(inner).downcast::<T>().map_err(|_| {
                Error::Type(format!(
                    "{name}: opaque tag matched `{tag}` but downcast failed"
                ))
            })
        }
        Some(v) => Err(Error::Type(format!(
            "{name}: arg {idx} must be opaque `{tag}`, got {}", v.type_name()
        ))),
        None => Err(Error::Eval(format!("{name}: missing arg {idx}"))),
    }
}

fn opaque<T: Send + Sync + 'static>(tag: &'static str, v: T) -> Value {
    Value::Opaque {
        tag: Arc::from(tag),
        inner: Arc::new(v) as Arc<dyn std::any::Any + Send + Sync>,
    }
}

fn vec_i64_to_value(xs: Vec<i64>) -> Value {
    Value::Vector(xs.into_iter().map(Value::Int).collect())
}

fn vec_f64_to_value(xs: Vec<f64>) -> Value {
    Value::Vector(xs.into_iter().map(Value::Float).collect())
}
"#;

/// Cljrs name -> Rust ident suitable for the shim fn. `gen-range` ->
/// `gen_range`. Anything non-ascii-alnum becomes `_`.
fn shim_ident(prefix: &str, clj: &str) -> String {
    let mut s = String::from(prefix);
    for c in clj.chars() {
        if c.is_ascii_alphanumeric() {
            s.push(c);
        } else {
            s.push('_');
        }
    }
    s
}

fn marshal_arg(out: &mut String, ty: &Type, idx: usize, clj: &str) -> Result<String, BindgenError> {
    let var = format!("a{idx}");
    let line = match ty {
        Type::I64 => format!("    let {var} = arg_i64(args, {idx}, \"{clj}\")?;\n"),
        Type::F64 => format!("    let {var} = arg_f64(args, {idx}, \"{clj}\")?;\n"),
        Type::Bool => format!("    let {var} = arg_bool(args, {idx}, \"{clj}\")?;\n"),
        Type::Str => format!("    let {var} = arg_str(args, {idx}, \"{clj}\")?;\n"),
        Type::VecI64 => format!("    let {var} = arg_vec_i64(args, {idx}, \"{clj}\")?;\n"),
        Type::VecF64 => format!("    let {var} = arg_vec_f64(args, {idx}, \"{clj}\")?;\n"),
        Type::Opaque(tag) => format!(
            "    let {var} = arg_opaque::<{tag}>(args, {idx}, \"{tag}\", \"{clj}\")?;\n"
        ),
    };
    out.push_str(&line);
    // Strings hand out an Arc<str>; pass `&*x` for &str arg sites.
    let pass = match ty {
        Type::I64 | Type::F64 | Type::Bool => var.clone(),
        Type::Str => format!("&*{var}"),
        Type::VecI64 | Type::VecF64 => var.clone(),
        Type::Opaque(_) => format!("&*{var}"),
    };
    Ok(pass)
}

/// Wrap a Rust expression of the configured `ret` type into a `Value`.
fn wrap_return(expr: &str, ret: &Type) -> String {
    match ret {
        Type::I64 => format!("Ok(Value::Int(({expr}) as i64))"),
        Type::F64 => format!("Ok(Value::Float(({expr}) as f64))"),
        Type::Bool => format!("Ok(Value::Bool({expr}))"),
        Type::Str => format!("Ok(Value::Str(Arc::from(({expr}).to_string().as_str())))"),
        Type::VecI64 => format!("Ok(vec_i64_to_value(({expr}).into_iter().collect()))"),
        Type::VecF64 => format!("Ok(vec_f64_to_value(({expr}).into_iter().collect()))"),
        Type::Opaque(tag) => format!("Ok(opaque(\"{tag}\", {expr}))"),
    }
}

fn write_fn_shim(out: &mut String, m: &Manifest, f: &Function) -> Result<(), BindgenError> {
    let ident = shim_ident("fn_", &f.clj_name);
    let _ = writeln!(out, "fn {ident}(args: &[Value]) -> Result<Value> {{");
    let mut passed = Vec::with_capacity(f.args.len());
    for (i, a) in f.args.iter().enumerate() {
        let ty = Type::parse(a)?;
        passed.push(marshal_arg(out, &ty, i, &f.clj_name)?);
    }
    let prefix = m
        .crate_
        .fn_prefix
        .clone()
        .unwrap_or_else(|| m.crate_.name.replace('-', "_"));
    let call_path = if prefix.is_empty() {
        f.name.clone()
    } else {
        format!("{prefix}::{}", f.name)
    };
    let call = if let Some(tpl) = &f.call {
        let mut s = tpl.clone();
        for (i, p) in passed.iter().enumerate() {
            s = s.replace(&format!("{{{i}}}"), p);
        }
        // The template is the call body; we still prepend the path so
        // users only have to write `seed_from_u64({0} as u64)` rather
        // than the full `Rng::seed_from_u64(...)`.
        if s.contains('(') {
            // template provides its own parens — just prefix the path
            // up to but excluding the trailing ident if any.
            // Simplest: use the call_path's namespace prefix.
            if let Some(idx) = call_path.rfind("::") {
                format!("{}::{}", &call_path[..idx], s)
            } else {
                s
            }
        } else {
            format!("{call_path}({s})")
        }
    } else {
        format!("{call_path}({})", passed.join(", "))
    };
    let ret = Type::parse(&f.returns)?;
    let _ = writeln!(out, "    let r = {call};");
    let _ = writeln!(out, "    {}", wrap_return("r", &ret));
    let _ = writeln!(out, "}}\n");
    Ok(())
}

fn write_method_shim(out: &mut String, me: &Method) -> Result<(), BindgenError> {
    let ident = shim_ident("method_", &me.clj_name);
    let _ = writeln!(out, "fn {ident}(args: &[Value]) -> Result<Value> {{");
    // arg 0 is the opaque receiver
    let _ = writeln!(
        out,
        "    let recv = arg_opaque::<{}>(args, 0, \"{}\", \"{}\")?;",
        me.on, me.on, me.clj_name
    );
    let mut passed = Vec::with_capacity(me.args.len());
    for (i, a) in me.args.iter().enumerate() {
        let ty = Type::parse(a)?;
        passed.push(marshal_arg(out, &ty, i + 1, &me.clj_name)?);
    }
    // Handles are stored as `Arc<T>`; methods generally need `&mut self`
    // for things like `gen_range` on rngs. We work around the lack of
    // unique ownership by going through `&*recv` and relying on interior
    // mutability where the foreign type provides it. ThreadRng's API
    // takes `&mut self` but its handle is `Cell<...>`-backed under the
    // hood; for true `&mut`-only handles users will need a wrapper that
    // provides interior mutability — phase 3.
    let recv_expr = "(&*recv).clone()";
    // The body of the method invocation. If a `call` template is given,
    // expand `{0}..{N}` against the passed exprs. Otherwise default to
    // `name(arg0, arg1, ...)`.
    let body = if let Some(tpl) = &me.call {
        let mut s = tpl.clone();
        for (i, p) in passed.iter().enumerate() {
            s = s.replace(&format!("{{{i}}}"), p);
        }
        s
    } else {
        format!("{}({})", me.name, passed.join(", "))
    };
    let call = format!(
        "{{ let mut __recv = {recv_expr}; __recv.{body} }}"
    );
    let ret = Type::parse(&me.returns)?;
    let _ = writeln!(out, "    let r = {call};");
    let _ = writeln!(out, "    {}", wrap_return("r", &ret));
    let _ = writeln!(out, "}}\n");
    Ok(())
}

fn write_install(out: &mut String, m: &Manifest) {
    let _ = writeln!(out, "pub fn install(env: &Env) {{");
    let _ = writeln!(out, "    let prev = env.current_ns();");
    let _ = writeln!(out, "    env.set_current_ns(\"{}\");", m.crate_.ns);
    for f in &m.fns {
        let ident = shim_ident("fn_", &f.clj_name);
        let _ = writeln!(out, "    bind(env, \"{}\", {ident});", f.clj_name);
    }
    for me in &m.methods {
        let ident = shim_ident("method_", &me.clj_name);
        let _ = writeln!(out, "    bind(env, \"{}\", {ident});", me.clj_name);
    }
    let _ = writeln!(out, "    env.set_current_ns(prev.as_ref());");
    let _ = writeln!(out, "}}");
}
