// AUTO-GENERATED by cljrs-bindgen. DO NOT EDIT.
// Source manifest binds crate `rand` v0.8 into namespace `cljrs.rand`.

#![allow(unused_imports, unused_variables, dead_code)]

use cljrs::env::Env;
use cljrs::error::{Error, Result};
use cljrs::value::{Builtin, Value};
use std::sync::Arc;
use rand::rngs::StdRng as Rng;
use rand::SeedableRng as _SeedableRng;
use rand::Rng as _RngTrait;


fn bind(env: &Env, name: &'static str, f: fn(&[Value]) -> Result<Value>) {
    env.define_global(name, Value::Builtin(Builtin::new_static(name, f)));
}

fn arg_i64(args: &[Value], idx: usize, name: &str) -> Result<i64> {
    match args.get(idx) {
        Some(Value::Int(i)) => Ok(*i),
        Some(v) => Err(Error::Type(format!(
            "{name}: arg {idx} must be int, got {}", v.type_name()
        ))),
        None => Err(Error::Eval(format!("{name}: missing arg {idx}"))),
    }
}

fn arg_f64(args: &[Value], idx: usize, name: &str) -> Result<f64> {
    match args.get(idx) {
        Some(Value::Float(f)) => Ok(*f),
        Some(Value::Int(i)) => Ok(*i as f64),
        Some(v) => Err(Error::Type(format!(
            "{name}: arg {idx} must be number, got {}", v.type_name()
        ))),
        None => Err(Error::Eval(format!("{name}: missing arg {idx}"))),
    }
}

fn arg_bool(args: &[Value], idx: usize, name: &str) -> Result<bool> {
    match args.get(idx) {
        Some(Value::Bool(b)) => Ok(*b),
        Some(v) => Err(Error::Type(format!(
            "{name}: arg {idx} must be bool, got {}", v.type_name()
        ))),
        None => Err(Error::Eval(format!("{name}: missing arg {idx}"))),
    }
}

fn arg_str(args: &[Value], idx: usize, name: &str) -> Result<Arc<str>> {
    match args.get(idx) {
        Some(Value::Str(s)) => Ok(Arc::clone(s)),
        Some(v) => Err(Error::Type(format!(
            "{name}: arg {idx} must be string, got {}", v.type_name()
        ))),
        None => Err(Error::Eval(format!("{name}: missing arg {idx}"))),
    }
}

fn arg_vec_i64(args: &[Value], idx: usize, name: &str) -> Result<Vec<i64>> {
    match args.get(idx) {
        Some(Value::Vector(xs)) => xs.iter().enumerate().map(|(i, v)| match v {
            Value::Int(n) => Ok(*n),
            other => Err(Error::Type(format!(
                "{name}: arg {idx}[{i}] must be int, got {}", other.type_name()
            ))),
        }).collect(),
        Some(Value::List(xs)) => xs.iter().enumerate().map(|(i, v)| match v {
            Value::Int(n) => Ok(*n),
            other => Err(Error::Type(format!(
                "{name}: arg {idx}[{i}] must be int, got {}", other.type_name()
            ))),
        }).collect(),
        Some(v) => Err(Error::Type(format!(
            "{name}: arg {idx} must be vector of int, got {}", v.type_name()
        ))),
        None => Err(Error::Eval(format!("{name}: missing arg {idx}"))),
    }
}

fn arg_vec_f64(args: &[Value], idx: usize, name: &str) -> Result<Vec<f64>> {
    match args.get(idx) {
        Some(Value::Vector(xs)) => xs.iter().enumerate().map(|(i, v)| match v {
            Value::Float(n) => Ok(*n),
            Value::Int(n) => Ok(*n as f64),
            other => Err(Error::Type(format!(
                "{name}: arg {idx}[{i}] must be number, got {}", other.type_name()
            ))),
        }).collect(),
        Some(Value::List(xs)) => xs.iter().enumerate().map(|(i, v)| match v {
            Value::Float(n) => Ok(*n),
            Value::Int(n) => Ok(*n as f64),
            other => Err(Error::Type(format!(
                "{name}: arg {idx}[{i}] must be number, got {}", other.type_name()
            ))),
        }).collect(),
        Some(v) => Err(Error::Type(format!(
            "{name}: arg {idx} must be vector of number, got {}", v.type_name()
        ))),
        None => Err(Error::Eval(format!("{name}: missing arg {idx}"))),
    }
}

fn arg_opaque<T: 'static + Send + Sync>(
    args: &[Value], idx: usize, tag: &str, name: &str,
) -> Result<Arc<T>> {
    match args.get(idx) {
        Some(Value::Opaque { tag: t, inner }) if t.as_ref() == tag => {
            Arc::clone(inner).downcast::<T>().map_err(|_| {
                Error::Type(format!(
                    "{name}: opaque tag matched `{tag}` but downcast failed"
                ))
            })
        }
        Some(v) => Err(Error::Type(format!(
            "{name}: arg {idx} must be opaque `{tag}`, got {}", v.type_name()
        ))),
        None => Err(Error::Eval(format!("{name}: missing arg {idx}"))),
    }
}

fn opaque<T: Send + Sync + 'static>(tag: &'static str, v: T) -> Value {
    Value::Opaque {
        tag: Arc::from(tag),
        inner: Arc::new(v) as Arc<dyn std::any::Any + Send + Sync>,
    }
}

fn vec_i64_to_value(xs: Vec<i64>) -> Value {
    Value::Vector(xs.into_iter().map(Value::Int).collect())
}

fn vec_f64_to_value(xs: Vec<f64>) -> Value {
    Value::Vector(xs.into_iter().map(Value::Float).collect())
}

fn fn_random(args: &[Value]) -> Result<Value> {
    let r = rand::random::<f64>();
    Ok(Value::Float((r) as f64))
}

fn fn_seeded_rng(args: &[Value]) -> Result<Value> {
    let a0 = arg_i64(args, 0, "seeded-rng")?;
    let r = Rng::seed_from_u64(a0 as u64);
    Ok(opaque("Rng", r))
}

fn method_gen_range(args: &[Value]) -> Result<Value> {
    let recv = arg_opaque::<Rng>(args, 0, "Rng", "gen-range")?;
    let a1 = arg_i64(args, 1, "gen-range")?;
    let a2 = arg_i64(args, 2, "gen-range")?;
    let r = { let mut __recv = (&*recv).clone(); __recv.gen_range(a1..a2) };
    Ok(Value::Int((r) as i64))
}

pub fn install(env: &Env) {
    let prev = env.current_ns();
    env.set_current_ns("cljrs.rand");
    bind(env, "random", fn_random);
    bind(env, "seeded-rng", fn_seeded_rng);
    bind(env, "gen-range", method_gen_range);
    env.set_current_ns(prev.as_ref());
}
